load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "client",
    srcs = ["client.py"],
    deps = [
        "@abseil-py//absl:app",
        "@abseil-py//absl/flags:flags",
    ],
)
