module(
    name = "borg_kv_store",
    version = "1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "abseil-cpp", version = "20260817.0")
bazel_dep(name = "googletest", version = "1.18.0.bcr.1")

bazel_dep(name = "rules_python", version = "2.0.1")
bazel_dep(name = "abseil-py", version = "2.4.0")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)

git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
    commit = "078ba7675c05bea2666c92d9a8abe200d8547655",
)
